---

- name: Resetting OpenLab equipment 
  hosts: station1-routers, station1-switches
  gather_facts: false

  tasks:
   - name: Reloading the equipment
     cli_command:
       command: reload
       prompt:
        - modified
        - reload
       answer:
        - n
        - y
     register: output

   - name: print output
     debug:
       var: output.stdout_lines
   - name: Wait
     wait_for_connection:
       delay: 10
